### ISSUE TITLE
drmdecrypt 1.0 doesn't work with SAMSUNG TV UE55KS7500U

### ISSUE THREAD

**Issue by piek** [decke/drmdecrypt#10]
Hi Guys,

I'm new of this community and I hope to find a solution to my problem.
I'm trying to decrypt the PVR taken from SAMSUNG UE55KS7500U on a hard drive.
For each recording I have five files with the following extensions:
.srf
.mdb
.inf
.cip
.ss

I copied all of them in the same directory where drmdecrypt.exe resides and started it with with the DOS command:
drmdecrypt - d -o C:\ filename.srf

Unfortunately I got the error: **scrambling info seems to be invalid!**
Any one can help me, please?

Thank you in advance!

**Comment by decke** [comment]
Series "K" (UE55**K**S7500U) is not supported at all. Samsung has changed the location of the encryption keys with every generation. Series C and D were quite easy because the keys were under the doormat but in later generations the keys were stored in the internal storage which required to modify the TV firmware.

drmdecrypt is focused on Series C and D Samsung TVs. Good luck!

**Comment by piek** [comment]
Not very happy about that but, ok :-) Thank you.
