### ISSUE TITLE
TS-File not playable

### ISSUE THREAD

**Issue by McCrafterIV** [decke/drmdecrypt#6]
Hello,

converting went fine without any problems, but the resulting ts file is not playable. I tried different methods and got the following log from VLC media player:
`ts demux error: libdvbpsi error (PSI decoder): PSI section too long`
I also wasn't able to convert the file to e.g. mp4 using ffmpeg.
How can I resolve this issue?

**Comment by decke** [comment]
Please try to answer the questions from the bug template as your report without details is near to worthless.

The short description is that Samsung did only encrypt the actual stream content but not the mpeg metadata for all frames. So all encrypted files look like real mpeg ts files for vlc etc.

**Comment by McCrafterIV** [comment]
Sorry, I haven't seen the bug template due to logging in after clicking on the "new issue" button. 
Because I don't know much about this stuff, I cant say much about the source other than this is a about 1 year old recording from I believe SAT.1 (not sure about the last part, but I can look this up if it helps). The channel isn't encrypted. I also sadly don't know the model and firmware version of the tv. I hope this is still enough information to resolve this issue. I also tried to decrypt the recording using DeSTRoi which worked without any errors but has also resulted in an unplayable file.

**Comment by McCrafterIV** [comment]
> The short description is that Samsung did only encrypt the actual stream content but not the mpeg metadata for all frames. So all encrypted files look like real mpeg ts files for vlc etc.
Can you explain this in a little bit more detail please? I sadly don't really understand what you mean

**Comment by decke** [comment]
At least the model or model year would be good to know because Samsung has changed a lot over time. It would also help if you can share a 10sec recording so I could try some decoding myself.

The mpeg ts file consists of packets with a fixed length. Each packet has a header (not encrypt) and content (AES encrypted).

https://github.com/decke/drmdecrypt/blob/e117fcbf0289cb460d6fab2263c17a9ffffdbab8/drmdecrypt.c#L214

So for a player or mpeg validation tools the encrypted mpeg file and it's packets look absolutely valid just the content of the frames is garbage.

**Comment by McCrafterIV** [comment]
Found the model number: UE40H6600SV. Can't provide a short recording unfortunately.
Solved my specific issue (haven't successfully decoded it, but don't need the decoding atm anymore), but would still be interested in knowing why it hasn't worked and how this could be fixed.

**Comment by decke** [comment]
This is a model H (2014) and it's not supported.
